### ISSUE TITLE
Checking whether UDP connection is alive during the call

### ISSUE THREAD

**Issue by raviraja0559** [versatica/OverSIP#93]
Is there any mechanism that whether Oversip UDP connection is open or not during the call.

Please find the below steps
1. Make a call with UDP connetion
2. Connection established
3.Sudden Net connection drops

In the above scenario how to check in oversip whether udp connection is alive or closed.

**Comment by ibc** [comment]
UDP is not a connection oriented transport. That's why SIP implements transaction timers and retransmissions.

P.S. Please use the mailing list for questions.

**Comment by raviraja0559** [comment]
I have gone through the code which contains the information about timers. But we are following timers of sip signalling. We need to know the connection udp status during the call. could you please suggest me.

**Comment by ibc** [comment]
There is NO way to know the "UDP connection status" because UDP is never connected or disconnected. Hope this is 100% clear.

You don't know if a SIP message (or any packet) sent over UDP will reach its destination or not (unless the destination receives it and sends you back another confirmation message).

You don't need to check OverSIP timers at all. This is how SIP works when carried over UDP.
